name: Create Calendar in GOOGLE
on:
  workflow_dispatch:
    inputs:
      date:
        required: true
        type: string
      summary:
        required: true
        type: string

env:
  GOOGLE_SERVICE_CREDS: ${{ secrets.CALENDAR_SERVICE_ACCOUNT }}
  CALENDAR_ID: ${{ secrets.CALENDAR_ID }} 

jobs:
  output_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip3 install --upgrade pip && pip3 install -r requirements.txt
      - name: Print the summary to STDOUT
        run: echo The tag is ${{ github.event.inputs.summary }} 

      - name: Print the date to STDOUT
        run: echo The date is ${{ github.event.inputs.date }} 

      - name: Output details
        run: python3 -m es_cal.cron_api.cron "${{ github.event.inputs.summary }}" ${{ github.event.inputs.date }} 
